routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

/*Route::get('/' , ['as' => '/' , 'uses' => 'App\Http\Controllers\StripeCustomerController@index']);
Route::group(['prefix' => 'stripe-customer' , 'as' => 'stripe-customer.'] , function() {
    Route::get('create' , ['as' => 'create' , 'uses' => 'App\Http\Controllers\StripeCustomerController@create']);
    Route::post('store' , ['as' => 'store' , 'uses' => 'App\Http\Controllers\StripeCustomerController@store']);
    Route::get('edit/{id}' , ['as' => 'edit' , 'uses' => 'App\Http\Controllers\StripeCustomerController@edit']);
    //Route::post('update' , ['as' => 'update' , 'uses' => 'App\Http\Controllers\StripeCustomerController@update']);
    Route::get('detail/{id}' , ['as' => 'detail' , 'uses' => 'App\Http\Controllers\StripeCustomerController@detail']);
});*/

resources/views/stripe/create.blade.php
<head>
    <meta charset="utf-8">
    <title>Create a customer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
    
<main class="main" style="width: 100%; padding-left: 5%; padding-right: 5%">

    <h2 class="title" style="text-align: center;">
        Create a customer
    </h2>

    <div style="padding-left: 35%; padding-right: 45%">
        <form method="POST" action="{{ route('stripe-customer.store') }}">
            @csrf
            <table class="table">
                <tr>
                    <th>Email*</th>
                    <td>
                        <input type="text" name="email" value="{{ old('email') }}" class="input-text input-right">
                        @include('parts.formErrors', ['attribute' => 'email'])
                    </td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>
                        <input type="text" name="description" value="{{ old('description') }}" class="input-text input-right">
                    </td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>
                        <input type="text" name="name" value="{{ old('name') }}" class="input-text input-right">
                    </td>
                </tr>
                <tr>
                    <th>Balance</th>
                    <td>
                        <input type="number" name="balance" value="{{ old('balance') }}" class="input-text input-right">
                    </td>
                </tr>
            </table>
            <input type="submit" name="submit" value="submit" style="margin-left: 60%">
        </form>
    </div>
</main>

resources/views/stripe/detail.blade.php
<head>
    <meta charset="utf-8">
    <title>Detail a customer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
    
<main class="main" style="width: 100%; padding-left: 5%; padding-right: 5%">

    <h2 class="title" style="text-align: center;">
        Detail a customer
    </h2>

    <div style="padding-left: 35%; padding-right: 45%">
        <table class="table">
           <tr>
                <th>Email</th>
                <td>{{ $customer->email }}</td>
            </tr>
            <tr>
                <th>Stripe customer ID</th>
                <td>{{ $customer->stripe_customer_id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ $customer->description }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ $customer->name }}</td>
            </tr>
            <tr>
                <th>Balance</th>
                <td>{{ $customer->balance }}</td>
            </tr>
        </table>
        <a href="{{ route('/') }}" style="margin-left: 60%">OK</a>
    </div>
</main>

resources/views/stripe/edit.blade.php
<head>
    <meta charset="utf-8">
    <title>Update a customer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
    
<main class="main" style="width: 100%; padding-left: 5%; padding-right: 5%">

    <h2 class="title" style="text-align: center;">
        Update a customer
    </h2>

    <div style="padding-left: 35%; padding-right: 45%">
        <form method="POST" action="{{ route('stripe-customer.store') }}">
            @csrf
            <table class="table">
                <tr>
                    <th>Description</th>
                    <td>
                        <input type="text" name="description" value="{{ old('description' , $customer->description) }}" class="input-text input-right">
                    </td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>
                        <input type="text" name="name" value="{{ old('description' , $customer->name) }}" class="input-text input-right">
                    </td>
                </tr>
                <tr>
                    <th>Balance</th>
                    <td>
                        <input type="number" name="balance" value="{{ old('balance' , $customer->balance) }}" class="input-text input-right">
                    </td>
                </tr>
            </table>
            <input type="hidden" name="id" value="{{ $customer->id }}">
            <input type="hidden" name="stripe_customer_id" value="{{ $customer->stripe_customer_id }}">
            <input type="submit" name="submit" value="submit" style="margin-left: 60%">
        </form>
    </div>
</main>

resources/views/stripe/index.blade.php
<head>
    <meta charset="utf-8">
    <title>Stripe customers list</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style type="text/css">
        .message {
            text-align: center;
            color: blue;
        }

        .alert {
            text-align: center;
            color: red;
        }
    </style>
</head>
    
<main class="main" style="width: 100%; padding-left: 5%; padding-right: 5%">

    <h2 class="title" style="text-align: center;">
        Lists All Customers
    </h2>

    <h2 class="title">
        <a href="{{ route('stripe-customer.create') }}" class="btn btn-primary btn-m" style="margin-left: 0px;">Create a customer</a>
    </h2>

    @include('parts.infoMsg')
    @include('parts.errorMsg')

        <table class="table">
            <tr>
                <th>Email</th>
                <th>Stripe customer ID</th>
                <th>Description</th>
                <th>Name</th>
                <th>Balance</th>
                <th>Updates a customer</th>
                <th>Retrieves a customer</th>
            </tr>

            @if(!$customers->isEmpty())
                @foreach ($customers as $customer)
                    <tr>
                        <td>{{ $customer->email }}</td>
                        <td>{{ $customer->stripe_customer_id }}</td>
                        <td>{{ $customer->description }}</td>
                        <td>{{ $customer->name }}</td>
                        <td>{{ $customer->balance }}</td>
                        <td><a href="{{ route('stripe-customer.edit' , ['id' => $customer->id]) }}" class="btn btn-primary btn-m edit-category" style="font-size: 12px;">Updates a customer</a></td>
                        <td><a href="{{ route('stripe-customer.detail' , ['id' => $customer->id]) }}" class="btn btn-primary btn-m" style="font-size: 12px;">Retrieves a customer</a></td>
                    </tr>
                @endforeach
            @endif
        </table>
</main>